target:
	mkdir -p $(BUILD_DIR)
	$(CC) -c brainfuck.c -o $(BUILD_DIR)/brainfuck.o $(CFLAGS) -I $(INCLUDE)
	$(CC) -c compiler.c -o $(BUILD_DIR)/compiler.o $(CFLAGS) -I $(INCLUDE)
	$(CC) -c arrays.c -o $(BUILD_DIR)/arrays.o $(CFLAGS) -I $(INCLUDE)
